// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmao4Z9j9mHktsK0BZIjnh0y4ydRl4G7I',
    appId: '1:74843371209:web:b0ab96a7821e5c66f33f18',
    messagingSenderId: '74843371209',
    projectId: 'travelblog-96026',
    authDomain: 'travelblog-96026.firebaseapp.com',
    storageBucket: 'travelblog-96026.appspot.com',
    measurementId: 'G-1E3PBPFCY3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzTDIBp-mmnM0UjTbiQ1VSSf381oP7kQw',
    appId: '1:74843371209:android:5b18a5f511b7a08bf33f18',
    messagingSenderId: '74843371209',
    projectId: 'travelblog-96026',
    storageBucket: 'travelblog-96026.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnQ_62vPbQzqHoYxDGXNXuG-OfDgDDSAg',
    appId: '1:74843371209:ios:d5172787af41d6eef33f18',
    messagingSenderId: '74843371209',
    projectId: 'travelblog-96026',
    storageBucket: 'travelblog-96026.appspot.com',
    iosBundleId: 'com.example.travelblog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnQ_62vPbQzqHoYxDGXNXuG-OfDgDDSAg',
    appId: '1:74843371209:ios:cd9d425d6adc1662f33f18',
    messagingSenderId: '74843371209',
    projectId: 'travelblog-96026',
    storageBucket: 'travelblog-96026.appspot.com',
    iosBundleId: 'com.example.travelblog.RunnerTests',
  );
}
